markdown: rdiscount
permalink: /:title
rdiscount extensions: [smart]
exclude: [ .gitignore, README.md, Gemfile, Gemfile.lock, Procfile, vendor, Rakefile, the_app.rb, elasticsearch, app ]
elasticsearch_host: 127.0.0.1:9200 # this is where elasticsearch is running
category_dir: /categories
exclude_from_search: 'no_index'

# let's embed some video you guys!
embedly:
  playerColor: "40aaef" # $accent_blue from screen.sass
  width: "660"
  height: "413"
  playButton: true
  embedType: "seo"
  controlsVisibleOnLoad: false

